name: "Schedule Test"
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: echo "Schedule triggered at $(date -u)"
